import type { Property, Project, Testimonial, BlogPost } from '@/types';

export const mockProperties: Property[] = [
  {
    id: '1',
    address: '123 Main St',
    city: 'Pleasantville',
    state: 'CA',
    zip: '90210',
    price: 750000,
    bedrooms: 3,
    bathrooms: 2,
    areaSqFt: 1800,
    description: 'Charming single-family home in a quiet neighborhood. Features a spacious backyard and updated kitchen. Perfect for families.',
    images: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    propertyType: 'House',
    yearBuilt: 1985,
    features: ['Hardwood Floors', 'Granite Countertops', 'Fenced Yard', '2-Car Garage', 'Furnished', 'Pool Access'],
    latitude: 34.0522,
    longitude: -118.2437,
    status: 'For Sale',
    postedDate: '2024-07-15T10:00:00Z',
    isVerified: true,
  },
  {
    id: '2',
    address: '456 Oak Ave',
    city: 'Metropolis',
    state: 'NY',
    zip: '10001',
    price: 1200000,
    bedrooms: 2,
    bathrooms: 2,
    areaSqFt: 1200,
    description: 'Modern apartment in the heart of the city. Stunning views, rooftop pool, and concierge service. Walk to shops and restaurants.',
    images: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    propertyType: 'Apartment',
    yearBuilt: 2018,
    features: ['City View', 'Rooftop Pool', 'Gym', 'Concierge', 'Valet Parking', 'Pool'],
    latitude: 40.7128,
    longitude: -74.0060,
    status: 'For Sale',
    postedDate: '2024-07-20T14:30:00Z',
    isVerified: false,
  },
  {
    id: '3',
    address: '789 Pine Ln',
    city: 'Suburbia',
    state: 'TX',
    zip: '75001',
    price: 450000,
    bedrooms: 4,
    bathrooms: 3,
    areaSqFt: 2500,
    description: 'Spacious townhouse with a community pool and park. Great school district. Ideal for growing families. Not furnished.',
    images: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    propertyType: 'Townhouse',
    yearBuilt: 2005,
    features: ['Community Pool', 'Playground', 'Attached Garage', 'Patio'],
    latitude: 32.7767,
    longitude: -96.7970,
    status: 'For Rent',
    postedDate: '2024-06-30T09:00:00Z',
    isVerified: true,
  },
   {
    id: '4',
    address: '101 River Rd',
    city: 'Riverside',
    state: 'FL',
    zip: '33301',
    price: 980000,
    bedrooms: 3,
    bathrooms: 2.5,
    areaSqFt: 2200,
    description: 'Beautiful waterfront condo with boat slip. Panoramic ocean views and luxury amenities. Gated community. Furnished option available.',
    images: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    propertyType: 'Condo',
    yearBuilt: 2010,
    features: ['Waterfront', 'Boat Slip', 'Ocean View', 'Fitness Center', 'Gated Community', 'Furnished'],
    latitude: 26.1224,
    longitude: -80.1373,
    status: 'Sold',
    postedDate: '2024-05-10T12:00:00Z',
    isVerified: true,
  },
  {
    id: '5',
    address: '22 Sky High Apt',
    city: 'Metropolis',
    state: 'NY',
    zip: '10002',
    price: 2500000,
    bedrooms: 4,
    bathrooms: 3.5,
    areaSqFt: 3000,
    description: 'Luxurious penthouse with private elevator and panoramic city views. Fully furnished with designer pieces.',
    images: ['https://placehold.co/600x400.png'],
    propertyType: 'Apartment',
    yearBuilt: 2022,
    features: ['Private Elevator', 'Panoramic View', 'Furnished', 'Smart Home System', 'Terrace'],
    status: 'For Sale',
    postedDate: '2024-07-25T10:00:00Z',
    isVerified: true,
  },
  {
    id: '6',
    address: '77 Green Valley',
    city: 'Pleasantville',
    state: 'CA',
    zip: '90211',
    price: 850000,
    bedrooms: 3,
    bathrooms: 2,
    areaSqFt: 1950,
    description: 'Eco-friendly home with solar panels and a large garden. No pool but very spacious.',
    images: ['https://placehold.co/600x400.png'],
    propertyType: 'House',
    yearBuilt: 2015,
    features: ['Solar Panels', 'Large Garden', 'Recycled Materials', 'Rainwater Harvesting'],
    status: 'For Sale',
    postedDate: '2024-07-22T10:00:00Z',
    isVerified: true,
  },
  {
    id: 'property-usa-1',
    address: '123 Liberty Ave',
    city: 'New York',
    state: 'NY',
    zip: '10001',
    price: 1250000,
    bedrooms: 2,
    bathrooms: 2,
    areaSqFt: 1100,
    description: 'Classic brownstone apartment in a prime NYC location.',
    images: ['https://placehold.co/600x400.png'],
    propertyType: 'Apartment',
    yearBuilt: 1910,
    latitude: 40.7128,
    longitude: -74.0060,
    status: 'For Sale',
    postedDate: '2024-07-01T00:00:00Z',
    isVerified: true,
  },
  {
    id: 'property-pakistan-1',
    address: '456 Gulberg Rd',
    city: 'Lahore',
    state: 'Punjab',
    zip: '54000',
    price: 250000, // USD equivalent for example
    bedrooms: 5,
    bathrooms: 4,
    areaSqFt: 3500,
    description: 'Spacious family home in a well-established Lahore neighborhood.',
    images: ['https://placehold.co/600x400.png'],
    propertyType: 'House',
    yearBuilt: 2005,
    latitude: 31.5204,
    longitude: 74.3587,
    status: 'For Sale',
    postedDate: '2024-07-05T00:00:00Z',
    isVerified: true,
  },
  {
    id: 'property-brazil-1',
    address: '789 Ipanema Beach Ave',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zip: '22410-002',
    price: 950000,
    bedrooms: 3,
    bathrooms: 3,
    areaSqFt: 1500,
    description: 'Stunning apartment with ocean views in Ipanema.',
    images: ['https://placehold.co/600x400.png'],
    propertyType: 'Apartment',
    yearBuilt: 1995,
    latitude: -22.9836,
    longitude: -43.2045,
    status: 'For Rent',
    postedDate: '2024-07-10T00:00:00Z',
    isVerified: true,
  },
];

export const mockProjectsData: Project[] = [
  {
    id: 'proj1',
    name: 'Skyline Towers',
    location: 'Metropolis Downtown',
    developer: 'Prestige Developers Inc.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'modern skyscraper residential',
    description: 'Luxury apartments with breathtaking city views and state-of-the-art amenities.',
    keyHighlights: ['Luxury Apartments', 'Rooftop Pool', 'Smart Homes'],
    amenities: ['Rooftop Pool', 'Gym', 'Concierge', 'Smart Homes', 'Private Cinema'],
    isVerified: true,
    status: 'Trending',
    timeline: 'Completion Q4 2025',
    learnMoreLink: '/new-projects#skyline-towers',
  },
  {
    id: 'proj2',
    name: 'Greenwood Villas',
    location: 'Suburbia Greens',
    developer: 'EcoBuild Homes Ltd.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'eco-friendly houses suburban',
    description: 'Eco-friendly villas nestled in nature, offering a sustainable and serene lifestyle.',
    keyHighlights: ['Eco-Friendly Villas', 'Community Garden', 'Solar Panels'],
    amenities: ['Solar Panels', 'Community Garden', 'Clubhouse', 'Jogging Tracks', 'Yoga Studio'],
    isVerified: true,
    status: 'Upcoming',
    timeline: 'Phase 1 Ready Q2 2025',
    learnMoreLink: '/new-projects#greenwood-villas',
  },
  {
    id: 'proj3',
    name: 'Commerce Hub',
    location: 'Central Business District',
    developer: 'UrbanConstruct Co.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'commercial building office',
    description: 'State-of-the-art commercial plaza with modern office spaces and retail outlets.',
    keyHighlights: ['Commercial Plaza', 'Prime Location', 'Flexible Office Spaces'],
    amenities: ['High-speed Internet', 'Ample Parking', 'Food Court', 'Conference Halls', '24/7 Security'],
    isVerified: false,
    status: 'Launched',
    timeline: 'Operational',
    learnMoreLink: '/new-projects#commerce-hub',
  },
  {
    id: 'proj4',
    name: 'Orchard County Plots',
    location: 'Pleasantville Outskirts',
    developer: 'Landmark Holdings',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'land plot development',
    description: 'Residential plots in a master-planned community with lush green spaces.',
    keyHighlights: ['Residential Plots', 'Gated Community', 'Easy Installments'],
    amenities: ['Parks & Green Areas', 'Community Center', 'School Inside', 'Hospital Nearby'],
    isVerified: true,
    status: 'Trending',
    timeline: 'Booking Open',
    learnMoreLink: '/new-projects#orchard-county',
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: 'testimonial1',
    name: 'Sarah K.',
    role: 'Homebuyer',
    quote: "Estate Explore made finding our dream home so easy! The verified listings gave us peace of mind, and the AI chat was surprisingly helpful.",
    imageUrl: 'https://placehold.co/80x80.png',
    dataAiHint: 'happy person portrait',
    rating: 5,
    successTag: "Found Home in Pleasantville",
  },
  {
    id: 'testimonial2',
    name: 'John B.',
    role: 'Real Estate Agent',
    quote: "Listing my properties on Estate Explore has significantly increased my leads. The platform is user-friendly and the agent tools are great.",
    imageUrl: 'https://placehold.co/80x80.png',
    dataAiHint: 'professional agent',
    rating: 4.5,
    successTag: "Increased Sales by 20%",
  },
  {
    id: 'testimonial3',
    name: 'Ahmed & Fatima',
    role: 'Investors',
    quote: "We found an amazing investment opportunity in a new project showcased on Estate Explore. The market insights helped us make an informed decision.",
    imageUrl: 'https://placehold.co/80x80.png',
    dataAiHint: 'couple smiling',
    rating: 5,
    successTag: "Invested in Skyline Towers",
  },
  {
    id: 'testimonial4',
    name: 'Maria L.',
    role: 'Renter',
    quote: "The search filters are fantastic! I found the perfect apartment to rent within my budget in just a few days. Highly recommend this platform.",
    imageUrl: 'https://placehold.co/80x80.png',
    dataAiHint: 'young woman student',
    rating: 4,
    successTag: "Rented Apartment in Metropolis",
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: 'blog1',
    title: 'How to Buy a Home in Pleasantville in 2025',
    slug: 'how-to-buy-home-pleasantville-2025',
    excerpt: 'Learn the essential steps to secure your dream home in Pleasantville with confidence this year.',
    content: "Buying a home is one of the most significant financial decisions you'll ever make. This guide provides a step-by-step process for navigating the Pleasantville real estate market in 2025. From getting pre-approved for a mortgage to closing the deal, we've got you covered.\n\nFirst, assess your financial health. Check your credit score and start saving for a down payment. A good rule of thumb is to have at least 20% of the home's purchase price, although some loan programs allow for less. Next, get pre-approved for a mortgage to understand your budget. This will show sellers that you are a serious buyer. Finally, find a great real estate agent who knows the Pleasantville area inside and out.",
    imageUrl: 'https://placehold.co/1200x630.png',
    dataAiHint: 'house keys contract',
    category: 'Buying Guide',
    author: 'Alice Wonderland',
    createdAt: '2024-07-28T10:00:00Z',
    status: 'published',
    tags: ['home buying', 'pleasantville', 'mortgage', 'real estate 101'],
  },
  {
    id: 'blog2',
    title: '5 Tips for Selling Your Plot Fast in Metropolis',
    slug: '5-tips-selling-plot-fast-metropolis',
    excerpt: 'Maximize your plot\'s value and attract buyers quickly with these expert selling strategies.',
    content: "Selling a plot of land can be different from selling a house. In the bustling market of Metropolis, here are five tips to ensure a quick and profitable sale.\n\n1. **Price it Right:** Research comparable land sales in your area. Overpricing can scare away potential buyers.\n2. **Clear the Land:** A clean, accessible plot is more appealing. Remove any debris, and consider getting a survey done to mark the boundaries clearly.\n3. **Highlight Potential:** Create marketing materials that showcase what could be built on the land—a beautiful home, a commercial building, etc.\n4. **Market Online:** Use platforms like Albatross Realtor to reach a wide audience of potential buyers and investors.\n5. **Be Patient but Responsive:** Land sales can sometimes take longer, but always be ready to answer inquiries promptly.",
    imageUrl: 'https://placehold.co/1200x630.png',
    dataAiHint: 'land plot for sale sign',
    category: 'Selling Tips',
    author: 'Bob The Builder',
    createdAt: '2024-07-25T14:30:00Z',
    status: 'published',
    tags: ['land selling', 'metropolis', 'investment', 'real estate tips'],
  },
  {
    id: 'blog3',
    title: 'Understanding Real Estate Market Trends in Suburbia',
    slug: 'understanding-real-estate-market-trends-suburbia',
    excerpt: 'Dive into the latest market insights for Suburbia to make informed investment decisions.',
    content: "Suburbia's real estate market is constantly evolving. This post breaks down the current trends, including median home prices, inventory levels, and days on market. We'll explore which neighborhoods are becoming hotspots and what buyers are looking for in a suburban home today. Whether you're buying, selling, or investing, understanding these trends is key to making a smart move.",
    imageUrl: 'https://placehold.co/1200x630.png',
    dataAiHint: 'market graph chart city',
    category: 'Market Insights',
    author: 'Carol Danvers',
    createdAt: '2024-07-22T09:00:00Z',
    status: 'published',
    tags: ['market trends', 'suburbia', 'investing', 'data'],
  },
  {
    id: 'blog4',
    title: 'Navigating Legal Aspects of Property Investment',
    slug: 'navigating-legal-aspects-property-investment',
    excerpt: 'A comprehensive guide to understanding the legalities involved in property investment to protect your assets.',
    content: "Real estate investment involves a complex web of legal requirements. This article covers the essentials, from understanding zoning laws and property titles to drafting airtight lease agreements. We'll also touch on tax implications and the importance of working with a qualified real estate attorney. Protecting your investment starts with understanding the law.",
    imageUrl: 'https://placehold.co/1200x630.png',
    dataAiHint: 'legal document gavel',
    category: 'Legal Advice',
    author: 'David Copperfield',
    createdAt: '2024-07-20T12:00:00Z',
    status: 'published',
    tags: ['legal', 'investment', 'contracts', 'property law'],
  },
  {
    id: 'blog5',
    title: 'Top 5 Amenities Homebuyers Are Looking For',
    slug: 'top-5-amenities-homebuyers-are-looking-for',
    excerpt: 'Discover the top features that can make your property stand out to potential buyers.',
    content: "What makes a buyer fall in love with a home? Often, it's the little extras. We've compiled a list of the top 5 amenities that are currently in high demand:\n\n1. **Home Office Space:** With the rise of remote work, a dedicated workspace is a must.\n2. **Outdoor Living Areas:** Patios, decks, and well-maintained backyards are huge selling points.\n3. **Updated Kitchens:** Modern, functional kitchens with energy-efficient appliances are always a hit.\n4. **Energy Efficiency:** Features like solar panels, good insulation, and smart thermostats are increasingly important.\n5. **Smart Home Technology:** Integrated security, lighting, and climate control offer convenience and appeal.",
    imageUrl: 'https://placehold.co/1200x630.png',
    dataAiHint: 'modern kitchen interior',
    category: 'Buying Guide',
    author: 'Alice Wonderland',
    createdAt: '2024-07-18T11:00:00Z',
    status: 'draft',
    tags: ['amenities', 'home features', 'selling tips'],
  },
];


export const getPropertyById = (id: string): Property | undefined => {
  return mockProperties.find(p => p.id === id);
};

export const getProjectById = (id: string): Project | undefined => {
  return mockProjectsData.find(p => p.id === id);
};

export const getTestimonialById = (id: string): Testimonial | undefined => {
  return mockTestimonials.find(t => t.id === id);
};

export const getBlogPostById = (id: string): BlogPost | undefined => {
  return mockBlogPosts.find(b => b.id === id);
};

export const getBlogPostBySlug = (slug: string): BlogPost | undefined => {
  return mockBlogPosts.find(b => b.slug === slug);
};
